#!/usr/bin/env python3

import os

__all__ = ['LUKSYPAM_FOLDER_NAME', 'CONFIG_FILE_NAME', 'USER_HOME',
           'USER_ROOT_FOLDER', 'USER_CONFIG_FILE', 'FORMAT_DRIVE_IN']

LUKSYPAM_FOLDER_NAME=".luksypam"
CONFIG_FILE_NAME="config.json"

USER_HOME=os.path.expanduser("~{}/".format(os.environ["PAM_USER"]))
USER_ROOT_FOLDER=USER_HOME + LUKSYPAM_FOLDER_NAME + "/"
USER_CONFIG_FILE=USER_ROOT_FOLDER + CONFIG_FILE_NAME
FORMAT_DRIVE_IN="ext4"
