#!/usr/bin/env python3

__all__ = ['LUKSYPAM_FOLDER_NAME', 'CONFIG_FILE_NAME',
           'FORMAT_DRIVE_IN', 'PROMPT_PASS', 'DEBUG_MSG_ENABLE',
           'NORMAL_ITER_TIME', 'WEAK_ITER_TIME', 'NORMAL_HASH_MODE',
           'WEAK_HASH_MODE', 'NORMAL_KEY_SIZE', 'WEAK_KEY_SIZE',
           'DEFAULT_MIN_CONTAINER_SIZE']

LUKSYPAM_FOLDER_NAME=".luksypam"
CONFIG_FILE_NAME="config.json"
FORMAT_DRIVE_IN="ext4"
PROMPT_PASS="Enter container '{}' password: "
DEBUG_MSG_ENABLE=False
NORMAL_ITER_TIME = 5000
WEAK_ITER_TIME = 2000
NORMAL_HASH_MODE = "sha512"
WEAK_HASH_MODE = "sha256"
NORMAL_KEY_SIZE = 512
WEAK_KEY_SIZE = 256
DEFAULT_MIN_CONTAINER_SIZE = 8
